language: node_js
node_js:
  - '10'
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsecret-1-dev          ; fi
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - rpm
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  docker run --rm --name electron -ti -d -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules electronuserland/electron-builder:wine
  docker exec electron npm install && npm prune
  docker exec electron npm run build:linux
  docker exec electron npm run build:windows
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true