language: node_js
node_js:
  - '8.16.1'
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsecret-1-dev          ; fi
  - yarn install --network-timeout 1000000
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - rpm
matrix:
  include:
  - os: windows
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  - yarn package-ci
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true