language: node_js
node_js:
  - '10'
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsecret-1-dev          ; fi
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  - yarn package-ci
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true